version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=greenplace_db
    volumes:
      - greenplace_pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    ports:
      - '8090:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=rhoggerrv@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1q2w3e4r5t6y
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  greenplace_pg_data:
  pgadmin_data:
